<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\tModLoader.targets" />
  <PropertyGroup>
    <AssemblyName>Reese</AssemblyName>
    <LangVersion>12.0</LangVersion>
  </PropertyGroup>

	<!-- Publicizer-->
	<ItemGroup>
		<PackageReference Include="Krafs.Publicizer" PrivateAssets="true" Version="2.2.1" />
		<Publicize Include="tModLoader" IncludeVirtualMembers="false" IncludeCompilerGeneratedMembers="false" />
	</ItemGroup>

</Project>
