<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\tModLoader.targets" />
  <PropertyGroup>
    <AssemblyName>Reese</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

	<!-- Add DragonLens for adding admin tools -->
	<ItemGroup>
		<Reference Include="DragonLens">
			<HintPath>lib\DragonLens.dll</HintPath>
		</Reference>
	</ItemGroup>

	<!-- Publicizer-->
	<ItemGroup>
		<PackageReference Include="Krafs.Publicizer" PrivateAssets="true" Version="2.2.1" />
		<Publicize Include="tModLoader" IncludeVirtualMembers="false" IncludeCompilerGeneratedMembers="false" />
		<Publicize Include="DragonLens" IncludeVirtualMembers="false" IncludeCompilerGeneratedMembers="false" />
	</ItemGroup>

</Project>
